services:
  app:
    build:
      context: .
    image: the_typing
    container_name: the_typing
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
