services:
  app:
    build:
      context: .
    image: the_typing
    container_name: the_typing
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    restart: always
    tty: true
    stdin_open: true

volumes:
  node_modules:
